### ISSUE TITLE
/docCount yes, but what about /hitCount ?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#131]
I think we're missing the ability to get back how many hits can be returned for a given query (with filters and buckets)? Maybe the docCount could be a little object containing both totalDocCount and hitDocCount?

What do you think? The cost of having to query norch & search-index many times goes down when the browser is the server, but good to keep a balance?

**Comment by eklem** [comment]
And this goes for search-index too, I think.

**Comment by eklem** [comment]
Sorry, that wasn't true I think. [The API docs has a sub-title called totalHits](https://github.com/fergiemcdowall/search-index/blob/master/doc/API.md#reading), but the actual documentation is missing.

**Comment by fergiemcdowall** [comment]
(Just fixed the documentation link to `totalHits`)

Yes, this is a design decision. I know it seems a bit clumsy, and its definitely up for discussion, but it sort of kind of makes sense:

- Calculating total hits requires extra computation. It makes sense to only calculate it if you actually want it, rather that forcing the user to always have it even if it is not needed
- Since `search-index` now streams results, there isn't an obvious place to put metadata for the resultset.

**Comment by eklem** [comment]
Nice. If it is like that already, just keep it =) But does norch have and endpoint for it?

**Comment by fergiemcdowall** [comment]
Ahhh- no. Good point- must be fixed.

**Comment by eklem** [comment]
Also, I think the design decision is a really good one. And good that the switch came now and not later. I'm amazed at the increased speed and reduced memory and CPU usage. It fixes a lot, and has a few downsides.

**Comment by fergiemcdowall** [comment]
`totalHits` should now be available in `0.8.5` on npm
