### ISSUE TITLE
Make it possible to send a JSON query object with parameters

### ISSUE THREAD

**Issue by fergiemcdowall** [fergiemcdowall/norch#63]
and document how it would work.

Is it possible to do this with a GET? Is it necessary to implement this as a POST?

**Comment by mewwts** [comment]
Alright. So here's a first proposal/draft of syntax. 
Today it's possible to search using a GET request to /search like this:
```http://localhost:3030/search?q=moscow&facets=topics&filter[topics][]=grain&filter[topics][]=acq&filter[places][]=ussr ```
Internally this is parsed into:
```javascript
{
    "query": {"*": ["moscow"]},
    "pageSize": 10,
    "facets": ["topics"],
    "filter": {"topics": ["grain", "acq"], "places": ["ussr"]} 
}
```
When creating queries, it might be useful to POST (or XGET for instance) a JSON, holding the query parameters, in the body of the request instead. What I propose is a similar, but a bit more flexible syntax:
```json
{
    "query": {
        "field": "*",
        "value": "moscow"
    },
    "facets": ["topics"],
    "filter": [
        {
            "field": "topics",
            "value": ["grain", "acq"]
        },
        {
            "field": "places",
            "value": ["ussr"]
        }
    ]
}
```
This is indeed a bit divergent (and a bit more complex?) from the internal query syntax as of today. Another idea would allow the fields to be lists as well:
```json
{
    "query": {
        "field": ["title", "body"],
        "value": ["moscow", "russia"]
    },
    "facets": ["topics"]
}
```
This is just some scribbling I've done. Feel free to 'shut it down' or propose something different. However, the reason for introducing a ```field``` and a ```value``` instead of using the field-name as a key is (at least) two-fold. ***First***, it allows you to dot your queries, even when your field name is in a variable, e.g
```javascript
var searchField = 'title';
var body = {
    query: {}
    facets: ['topics']
};
body.query[searchField] = 'mats';
```
versus:
```javascript

var searchField = 'title';
var body = {
    query: {
        field: searchField,
        value: ['mats']
    },
    facets: ['topics']
};
````
***Second***, it allows putting multiple fields in a list like shown above.

Also, it's useful to keep in mind whatever functionality may come later, and what we may add to our syntax without making breaking changes. For example, the above could surely be generalized into allowing ```query``` to be a list, and then allow a ```bool```-query of some sorts.

**Comment by mewwts** [comment]
By making a more complex query language, search by altering the URL may become harder. [Elasticsearch](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-uri-request.html) has a simple URI search implemented, but it is not nearly as complex as the Query DSL. 

Is being able to represent a search, with filters and facets completely in the URI important?
Do we wish to maintain two different ways of expressing a query?

Also I think it is better if such a DSL is compatible all the way down to search-index, rather than requiring lots of custom parsing in whatever interface (Norch or something else?) one chooses for his or hers search-index.

**Comment by eklem** [comment]
I think it is important. Two reasons:
* Ability to share a search with others
* Easily integrate links to a spesific search from other pages in your solution

**Comment by fergiemcdowall** [comment]
thinking...

**Comment by eklem** [comment]
My suggestion is that we go for the JSON query object and that we make a subset of that available from the URL. The stuff we don't get to describe in the URL will fallback to something predefined?

**Comment by fergiemcdowall** [comment]
Sending queries as JSON is now the default in Norch because:

1. Its more expressive than HTTP parameters
2. It allows Norch to simply reuse the `search-index` API
3. It is easier for the machines to create queries in JSON
