### ISSUE TITLE
Documentation: Geographical proximity sorting

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/norch#80]
Not strictly needed for the https://github.com/fergiemcdowall/norch/issues/79 , but good to have.

**Comment by fergiemcdowall** [comment]
Sorting is a slightly bigger change. Just now, results are always sorted on tf-idf score, but it would be great if you could define other fields to sort on (price, height, etc, etc.)

Geographical proximity is a special case because you are sorting on a value that is derived query time, but it could absolutely be done

**Comment by eklem** [comment]
Leave it be for now, we'll understand when it's important to do.

**Comment by fergiemcdowall** [comment]
I think that the concept of sorting on arbitrary fields is something that could be in the code at some point in the future

**Comment by fergiemcdowall** [comment]
I believe that some magic can be done here already with geohashes...

**Comment by eklem** [comment]
Sooo, with geohashes, this could be a case for `search-index-cookbook` ?

**Comment by eklem** [comment]
I'll close this an make an issue over at `search-index-cookbook`.
